
export interface IAppItemFullDetailIos {
    id: number,
    appId: string,
    title: string,
    url: string,
    description: string,
    icon: string,
    genres: [string],
    genreIds: [string],
    primaryGenre: string,
    primaryGenreId: number,
    contentRating: string,
    languages: [string],
    size: string,
    requiredOsVersion: string,
    released: string,
    updated: string,
    releaseNotes: string,
    version: string,
    price: 0,
    currency: string,
    free: boolean,
    developerId: number,
    developer: string,
    developerUrl: string,
    developerWebsite: string,
    score: number,
    reviews: number,
    currentVersionScore: number,
    currentVersionReviews: number,
    screenshots: [string],
    ipadScreenshots: [string],
    appletvScreenshots: [],
    supportedDevices:[string]
}